import {ref} from 'vue'

export const products = ref([
  {
    id: 1,
    sku: "BRG-001",
    name: "Beras 5kg",
    price: 65000,
    category: "Sembako",
    image: "/src/assets/rice.svg",
  },
  {
    id: 2,
    sku: "BRG-002",
    name: "Minyak Goreng 2L",
    price: 38000,
    category: "Sembako",
    image: "/src/assets/minyak-goreng.svg",
  },
  {
    id: 3,
    sku: "BRG-003",
    name: "Gula Pasir 1kg",
    price: 14500,
    category: "Sembako",
    image: "/src/assets/sugar.svg",
  },
  {
    id: 4,
    sku: "BRG-004",
    name: "Mie Instan",
    price: 3500,
    category: "Makanan",
    image: "/src/assets/noodles.svg",
  },
  {
    id: 5,
    sku: "BRG-005",
    name: "Sarden",
    price: 12000,
    category: "Makanan",
    image: "/src/assets/sarden.svg",
  },
  {
    id: 6,
    sku: "BRG-006",
    name: "Es Teh",
    price: 5000,
    category: "Minuman",
    image: "/src/assets/tea.svg",
  },
  {
    id: 7,
    sku: "BRG-007",
    name: "Air Mineral",
    price: 4000,
    category: "Minuman",
    image: "/src/assets/water.svg",
  },
  {
    id: 8,
    sku: "BRG-008",
    name: "Kopi",
    price: 18000,
    category: "Minuman",
    image: "/src/assets/coffee.svg",
  },
  {
    id: 9,
    sku: "BRG-009",
    name: "Sabun",
    price: 4500,
    category: "Kebutuhan Rumah",
    image: "/src/assets/soap.svg",
  },
  {
    id: 10,
    sku: "BRG-010",
    name: "Pasta Gigi",
    price: 9500,
    category: "Kebutuhan Rumah",
    image: "/src/assets/toothpaste.svg",
  },
  {
    id: 11,
    sku: "BRG-011",
    name: "Susu",
    price: 18000,
    category: "Minuman",
    image: "/src/assets/milk.svg",
  },
  {
    id: 12,
    sku: "BRG-012",
    name: "Roti Tawar",
    price: 15000,
    category: "Makanan",
    image: "/src/assets/bread.svg",
  },
]);
